### PR TITLE
Update dependencies + fix tests

### PR DESCRIPTION
**Pull request by lenovouser**
Really need TypeScript 5.0 support, thought I'd try to update everything in hopes of accelerating its release.

### CODE REVIEW

**Comment by lenovouser** [comment]
This should check this point

>  Update Typescript to v5 in dev dependencies and make sure tests are passing

in #60. Not sure how to add backwards compatibility tests with TypeScript 4.0 though.

**Comment by gund** [comment]
Hey, thanks for the PR!
This helps a lot with the update already!
Let's run CI to see if we can merge this.

**Comment by lenovouser** [comment]
Okay 👍🏻 Gave you push permissions to the fork, otherwise I will be able to try and debug the backwards compatibility tests in 1-2 hours.

**Comment by lenovouser** [comment]
@gund CI doesn't run automatically apparently

**Comment by lenovouser** [comment]
Added a test for TypeScript 4 now that I saw and worked with the other backwards compatibility test, so this:

> Add backwards compatibility tests for Typescript v4

Should be done as well, in case the CI runs through.

**Comment by gund** [comment]
Yeah looks like I need to approve CI run after every new push. Let's see if that works.

**Comment by gund** [comment]
Looks like all but TS v3 BC check is failing with the typescript error:
```
src/utils/stringifyJSDocTagInfoText.ts:10:35 - error TS2339: Property 'text' does not exist on type 'never'.

    10     : ts.displayPartsToString(tag.text);
```
Which is strange as we did not change any code for the new TS version...

**Comment by lenovouser** [comment]
Hmm, last issue is weird. Apparently the types between the different TypeScript versions are so far apart that `JSDocTagInfo` seems to have changed completely. I could do a type cast to `any`, the tests run after that. It's dirty though. What do you think?

Screenshot 2023-03-30 at 17 55 59

**Comment by lenovouser** [comment]
@gund locally all tests that are executed in the CI work now, let's hope it works online as well 😅🤞🏻

**Comment by gund** [comment]
Looks like it's working now! Great job on fixing this, thanks!

**Comment by lenovouser** [comment]
Thanks for creating this plugin!

**Comment by gund** [comment]
This has been published in `v1.4.0-next.1`.
Would you be able to verify if it works as expected before I release this on latest?

**Comment by lenovouser** [comment]
@gund everything seems to work for me!

**Pull request merged**
